import { DATA, OWN, IDS, GRADE_LABEL, DIRECT_LABEL } from '../data/pokemon-data.js';
import { MOVE_META, AXIS_LABEL } from '../data/meta-data.js';
import { battleTypes, eff, norm, cho, search } from '../core/type-system.js';
import { defenseProfile } from '../core/defense-engine.js';
import { abilityContext, abilitySummary, abilityImpact, bestAbilityMove, canSwitchOutAgainst } from '../core/ability-engine.js';
import { profile, bestFor, gradeBadge, matchupGrade, directGrade, axisGapForCombo } from '../core/matchup-engine.js';
import { inferMega, estimateOpponent, scenarioMegaForLead, scenarioMegaForPokemon, rankFMPlans, forcedLeadPlanScore, leadFirstAction, leadReason, leadConfidence, leadCounterPlan, withJosa, objectJosa, turnLine, planMode, likelyBackPlan, scenarioWinAxis, orderCombo } from '../core/selection-engine.js';
import { enemyMoveScenariosV42, exchangeAudit, speedProfileV42 } from '../core/speed-engine.js';
import { formatDefenseAxis as defenseAxisText } from './formatters.js';

const $=x=>document.getElementById(x);
let states=[],team=[],modalSlot=0;

export function renderTeam(){ $('teamStrip').innerHTML=IDS.map(id=>{let o=OWN[id];return `<div class="mon"><b>${o.name}</b>${o.item} · ${o.ability}<br>${o.moves.join(' / ')}</div>`}).join('') }

export function slots(){states=[];$('slots').innerHTML='';for(let i=0;i<6;i++){let d=document.createElement('div');d.className='slot';d.innerHTML=`<label>상대 ${i+1}</label><div class="iw"><input class="poke" placeholder="이름 일부 입력"><button class="clear">×</button></div><div class="sugs hidden"></div><div class="help">Enter로 최상단 확정</div>`;$('slots').appendChild(d);wire(d,i)}}

export function wire(d,i){let inp=d.querySelector('input'),menu=d.querySelector('.sugs'),st={inp,menu,items:[],active:0,selected:null};states[i]=st;function up(){let ex=states.map((x,j)=>j!==i&&x?.selected?x.selected.name:null).filter(Boolean);st.items=search(inp.value,ex);st.active=0;draw(st)}inp.oninput=()=>{st.selected=null;up()};inp.onfocus=()=>{modalSlot=i;up()};inp.onkeydown=e=>{if(e.key==='ArrowDown'){e.preventDefault();st.active=Math.min(st.active+1,st.items.length-1);draw(st)}else if(e.key==='ArrowUp'){e.preventDefault();st.active=Math.max(0,st.active-1);draw(st)}else if(e.key==='Enter'){e.preventDefault();if(st.items.length)choose(st,st.items[st.active]||st.items[0],true)}else if(e.key==='Escape')menu.classList.add('hidden')};d.querySelector('.clear').onclick=()=>{st.selected=null;inp.value='';inp.focus()}}

export function draw(st){if(!st.items.length){st.menu.innerHTML='<div class="sug"><small>일치 결과 없음</small></div>'}else st.menu.innerHTML=st.items.map((p,i)=>`<div class="sug ${i===st.active?'active':''}" data-n="${p.name}"><span><b>${p.name}</b> <small>#${p.rank}</small></span><span>${p.types.map(t=>`<i class="pill">${t}</i>`).join('')}${DATA.megaOptions[p.name]?'<i class="pill mega">메가 가능</i>':''}</span></div>`).join('');st.menu.querySelectorAll('[data-n]').forEach(el=>el.onmousedown=e=>{e.preventDefault();choose(st,DATA.roster.find(x=>x.name===el.dataset.n),true)});st.menu.classList.remove('hidden')}

export function chooseBase(st,p,next){st.selected=p;st.inp.value=p.name;st.menu.classList.add('hidden');if(next){let i=states.indexOf(st);if(i<5)setTimeout(()=>states[i+1].inp.focus(),0)}}


export function choose(st,p,advance=true){
  const r=chooseBase(st,p,advance);
  if(states.length===6&&states.every(x=>x.selected)&&$('formPanel').classList.contains('hidden'))form();
  return r;
}
export function getTeam(){let t=states.map(s=>s.selected);if(t.some(x=>!x)){alert('6마리를 모두 Enter로 확정하세요.');return null}if(new Set(t.map(x=>x.name)).size<6){alert('중복 포켓몬이 있습니다.');return null}return t}

export function analyze(){
 team=getTeam();if(!team)return;let chosenMega=$('megaSelect').value||'',manualLeadName=$('manualLeadSelect').value||'',megaHyp=inferMega(team,chosenMega),megaName=chosenMega,leadStyle=$('leadStyle').value||'auto',autoModel=estimateOpponent(team,megaName,'',leadStyle),model=manualLeadName?estimateOpponent(team,megaName,manualLeadName,leadStyle):autoModel,plans=rankFMPlans(team,megaName,model);if(manualLeadName){let forcedEnemy=team.find(p=>p.name===manualLeadName),forcedMega=scenarioMegaForLead(model,manualLeadName,megaName);plans.sort((a,b)=>forcedLeadPlanScore(b,forcedEnemy,forcedMega)-forcedLeadPlanScore(a,forcedEnemy,forcedMega))}let top=plans[0],rankedCombos=[];
 for(const p of plans)if(!rankedCombos.some(x=>x.combo.join('|')===p.combo.join('|')))rankedCombos.push(p);
 let seq=orderCombo(top.combo,top.lead,top.win,team,model,megaName),mode=planMode(top,team,model,megaName),lead=top.lead;
 $('resultPanel').classList.remove('hidden');$('matchPanel').classList.remove('hidden');$('planPanel').classList.remove('hidden');
 let set1=model.setHypotheses[0],setText=set1?set1.set.map(x=>x.name).join(' / '):model.predicted.map(x=>x.name).join(' / ');
 $('summary').textContent=`${model.arch.name} 유형으로 판정. ${manualLeadName?`사용자 예상 선봉 ${objectJosa(manualLeadName)} 고정해 조건부 계산했습니다. `:''}팀 전체 메가 1순위는 ${megaHyp.name||'불명'}(${megaHyp.confidence})이며, 실제 계산은 예상 3마리 조합별 메가 후보를 따로 적용했습니다. 최유력 조합은 ${setText}. 우리 60개 계획을 ${model.scenarios.length}개 선출·선봉 시나리오에 대조했습니다.`;
 let stability=top.catWeight<.04&&top.worst>8?'높은 재현성':top.catWeight<.12&&top.worst>0?'조건부 안정':'선봉 사고 위험';$('confidence').textContent=stability;
 $('picks').innerHTML=seq.map((id,i)=>{let o=OWN[id],label=i===0?'FM 추천 선봉':i===2?(mode==='집중형'?'후반 승리축':'마지막 보존 카드'):'중간 완충·연결',jobs=(top.base.contributions[id]?.jobs||[]).slice(0,3).map(x=>x.p.name).join('·')||'선봉 복구와 역할 연결';return `<div class="pick ${i===0?'lead':''}"><span class="score">${label}</span><span class="role">${o.role}</span><h3>${o.name}</h3><p><b>고유 임무:</b> ${jobs}</p><p>${o.summary}</p><p class="build">${o.item} · ${o.ability}<br>${o.moves.join(' / ')}</p></div>`}).join('');
 let worst=top.outcomes.filter(x=>x.sc.weight>=.025).sort((a,b)=>a.score-b.score)[0],worstText=worst?`${worst.sc.lead.name} 선봉＋${worst.sc.set.map(x=>x.name).join('·')} 시나리오에서 ${worst.opening.label}`:'유의미한 사고 시나리오 없음';
 $('order').innerHTML=`<strong>배치:</strong> ${seq.map(x=>OWN[x].name).join(' → ')}<br><strong>최악 시나리오:</strong> ${worstText}<br><strong>FM 원칙:</strong> ${manualLeadName?`${manualLeadName} 선봉을 고정하되, 그 뒤에 함께 나올 가능성이 높은 두 마리까지 처리 가능한 선출을 우선했습니다.`:'1순위 선봉을 맞히는 계획보다 2·3순위 역선봉에도 포켓몬을 공짜로 잃지 않는 계획을 우선했습니다.'}`;
 $('enemyScenarios').innerHTML=model.setHypotheses.slice(0,4).map((h,i)=>{let l=h.leads[0],pct=Math.round(h.weight*100),moves=h.set.map(p=>{let pr=profile(p,h.megaName);return `<b>${p.name}</b>: ${(pr.commonMoves||[]).slice(0,4).join('·')||pr.pattern}`}).join('<br>');return `<div class="scenario-card ${i===0?'primary':''}"><h4>${i+1}순위 · ${h.set.map(x=>x.name).join(' / ')}</h4><p><b>내부 조합 예상도:</b> ${pct}점 · <b>유력 선봉:</b> ${l.p.name}<br><b>이 조합의 예상 메가:</b> ${h.megaName||'없음/불명'}</p><div class="meter"><span style="width:${Math.max(4,pct)}%"></span></div><p>${moves}</p></div>`}).join('');
 let leadTop=model.leadPredicted,autoLeadTop=autoModel.leadPredicted,leadConf=leadConfidence(autoModel);
 $('leadForecast').innerHTML=`<div class="audit"><b>아키타입: ${autoModel.arch.name}</b><p>${autoModel.arch.note}<br><b>예측 신뢰도:</b> ${leadConf.label} — ${leadConf.note}<br><small>점수는 실제 출전 확률이 아니라 입력한 6마리 안의 상대 비교값입니다.</small></p></div>`+autoLeadTop.map((p,i)=>{let lm=scenarioMegaForLead(autoModel,p.name,megaName),cp=leadCounterPlan(p,top.combo,lm,lead);return `<div class="audit"><b>${i+1}순위 ${p.name} · 선봉 예상도 ${Math.round((autoModel.leads[p.name]||0)*100)}점</b><p><b>근거:</b> ${leadReason(p,team)}<br><b>예상 첫 행동:</b> ${leadFirstAction(p)}<br><b>현재 추천 선출의 대응:</b> ${cp.direct}<br><b>추천 선봉 기준:</b> ${cp.recover}</p></div>`}).join('');
 let manualBox=$('manualLeadBox');if(manualLeadName){let enemy=team.find(p=>p.name===manualLeadName),lm=scenarioMegaForLead(model,manualLeadName,megaName),byLead=IDS.map(id=>plans.find(r=>r.lead===id)).filter(Boolean).sort((a,b)=>forcedLeadPlanScore(b,enemy,lm)-forcedLeadPlanScore(a,enemy,lm)),cards=byLead.slice(0,3).map((r,i)=>{let dg=directGrade(enemy,r.lead,lm),eg=matchupGrade(enemy,r.lead,lm),line=turnLine(enemy,r.lead,r.combo,lm),comboNames=r.combo.map(x=>OWN[x].name).join(' / '),forcedScore=forcedLeadPlanScore(r,enemy,lm);return `<div class="audit"><b>${i+1}순위 우리 선봉: ${OWN[r.lead].name}</b><p><b>직접 대면:</b> ${DIRECT_LABEL[dg]} · <b>후출 등급:</b> ${GRADE_LABEL[eg]}<br><b>추천 선출:</b> ${comboNames}<br><b>1턴 행동:</b> ${line.action}<br><b>선봉 고정 종합점수:</b> ${forcedScore.toFixed(1)} · 시나리오 최악 ${r.worst.toFixed(1)}</p></div>`}).join('');$('manualLeadResult').innerHTML=`<div class="audit"><b>상대 선봉 고정: ${manualLeadName}</b><p><b>가장 바람직한 우리 선봉:</b> ${OWN[top.lead].name}<br><b>상대 예상 첫 행동:</b> ${leadFirstAction(enemy)}<br><b>선택 기준:</b> 정면 대면뿐 아니라 ${withJosa(manualLeadName)} 같이 나올 후발 두 마리, 교체 경로, 후반 승리축까지 포함했습니다.</p></div>`+cards;manualBox.classList.remove('hidden')}else{manualBox.classList.add('hidden');$('manualLeadResult').innerHTML=''};
 $('turnTree').innerHTML=leadTop.map((p,i)=>{let lm=scenarioMegaForLead(model,p.name,megaName),line=turnLine(p,lead,top.combo,lm),follow=likelyBackPlan(p,line,lead,top.combo,model,lm),cl=line.catastrophic?'danger':line.kind==='stay'||line.kind==='switch'||line.kind==='fastpivot'?'safe':'';return `<div class="tree-row ${cl}"><b>${i+1}순위 ${p.name}가 나오면 — ${line.label}</b><p><b>상대 예상:</b> ${leadFirstAction(p)}<br><b>우리 1턴:</b> ${line.action}${follow?'<br><b>다음 분기:</b> '+follow:''}</p></div>`}).join('');
 $('oppLikely').innerHTML=model.setHypotheses.slice(0,3).map((h,i)=>`<p><b>가설 ${i+1}. ${h.set.map(x=>x.name).join(' / ')}</b> · 내부 조합 예상도 ${Math.round(h.weight*100)}점<br><small>선봉 ${h.leads[0].p.name} → 후발 ${h.set.filter(x=>x.name!==h.leads[0].p.name).map(x=>x.name).join('·')} · 예상 메가 ${h.megaName||'불명'}</small></p>`).join('')+`<p><small>현재 아키타입: ${model.arch.name}. 팀 전체 메가 1순위: ${megaHyp.name||'불명'} — ${megaHyp.reason}. 직접 지정하면 모든 시나리오에 그 형태를 고정합니다.</small></p>`;
 let win=OWN[top.win];if(mode==='집중형')$('winAxis').innerHTML=`<p><b>집중형:</b> ${win.name}을 후반에 통과시키는 플랜.</p><p>${win.summary}</p><p><b>먼저 약화:</b> ${(top.base.blockers||[]).slice(0,3).map(x=>x.p.name).join(', ')||'뚜렷한 단독 방해 카드가 적음'}</p>`;else{let jobs=seq.map(id=>`<b>${OWN[id].name}</b> → ${(top.base.contributions[id]?.jobs||[]).slice(0,2).map(x=>x.p.name).join('·')||'대면 복구'}`).join('<br>');$('winAxis').innerHTML=`<p><b>분업형:</b> 예상 3마리를 담당별로 끊는 플랜.</p><p>${jobs}</p><p>상대 마지막 포켓몬이 확인될 때까지 그 담당 카드를 보존합니다.</p>`}
 let ownLeadPlans=top.combo.map(id=>plans.find(x=>x.combo.join('|')===top.combo.join('|')&&x.lead===id)).sort((a,b)=>b.robust-a.robust);
 $('leadRisk').innerHTML=ownLeadPlans.map((r,i)=>{let cats=r.outcomes.filter(x=>x.opening.catastrophic&&x.sc.weight>=.02).slice(0,3).map(x=>x.sc.lead.name),rec=r.outcomes.filter(x=>x.opening.kind==='switch'&&x.sc.weight>=.02).slice(0,3).map(x=>x.sc.lead.name);return `<div class="audit"><b>${i+1}위 선봉 ${OWN[r.lead].name}</b><p>강건 점수 ${r.robust.toFixed(1)} · 최악 ${r.worst.toFixed(1)}<br>${cats.length?'복구 불가 위험: '+[...new Set(cats)].join(', '):'주요 시나리오에서 즉시 붕괴 없음'}${rec.length?'<br>후출 복구: '+[...new Set(rec)].join(', '):''}</p></div>`}).join('');
 $('alternatives').innerHTML=rankedCombos.slice(1,4).map((r,i)=>`<div class="audit"><b>차선 ${i+1}: ${OWN[r.lead].name} 선봉 · ${r.combo.map(x=>OWN[x].name).join(' / ')}</b><p>강건 점수 ${r.robust.toFixed(1)} · 사고 가중치 ${Math.round(r.catWeight*100)}점. ${r.base.hardGaps.length?'강한 후출 답 부족: '+r.base.hardGaps.join(', '):'고확률 상대에 큰 단독 구멍 없음'}.${r.base.axisWarnings?.length?' 내구축 경고: '+r.base.axisWarnings.slice(0,2).join(' / '):''}</p></div>`).join('');
 let samples=(set1?.set||model.predicted),sampleMega=set1?.megaName||megaName;$('sampleManual').innerHTML=samples.map(p=>{let pr=profile(p,sampleMega),arr=bestFor(p,sampleMega).arr.filter(x=>top.combo.includes(x.id)).sort((a,b)=>b.grade-a.grade),b=arr[0];return `<div class="sample"><b>${p.name} · ${pr.precision}</b><p><b>특성:</b> ${abilitySummary(p,sampleMega)}<br><b>특성 영향:</b> ${abilityImpact(p,sampleMega)}<br><b>내구 판단:</b> ${defenseProfile(p,sampleMega).label} → ${defenseProfile(p,sampleMega).recommendation==='physical'?'물리 우선':defenseProfile(p,sampleMega).recommendation==='special'?'특수 우선':'축 고정 금지'}<br><b>가장 흔한 축:</b> ${(pr.commonMoves||[]).join(' / ')||pr.pattern}<br><b>우리 담당:</b> ${OWN[b.id].name} ${GRADE_LABEL[b.grade]} — ${b.move}<br><b>계획:</b> ${pr.winPlan}</p></div>`}).join('');
 $('fmValidation').innerHTML=`<div class="kpi"><strong>60</strong><small>우리 선출·선봉 계획</small></div><div class="kpi"><strong>${model.scenarios.length}</strong><small>상대 조합·선봉 시나리오</small></div><div class="kpi"><strong>${Math.round(top.catWeight*100)}</strong><small>사고 가중치(낮을수록 좋음)</small></div><div class="kpi"><strong>${top.worst.toFixed(1)}</strong><small>주요 시나리오 최악 점수</small></div>`;
 let bridge=seq[1],cleaner=seq[2],late=mode==='집중형'?`${OWN[cleaner].name}을 마지막까지 보존해 정리합니다. 담당 카운터가 남아 있으면 전개를 미룹니다.`:`상대 마지막 포켓몬이 확인될 때까지 담당 카드를 맞춰 보존합니다.`;$('phases').innerHTML=`<div class="phase"><b>초반</b><p>${OWN[lead].name}로 시작. 1턴 분기표대로 유지·교체·교환을 정하고, 없는 안전 후출을 만들어내려 하지 않습니다.</p></div><div class="phase"><b>중반</b><p>${set1?set1.set.slice(0,2).map(p=>p.name).join('·'):model.predicted.slice(0,2).map(p=>p.name).join('·')}의 도구와 기술을 확인해 가설 1·2순위를 갱신하고, 담당 카드의 체력을 보존합니다.</p></div><div class="phase"><b>후반</b><p>${late}</p></div>`;
 let preserve=[],avoid=[];$('matchBody').innerHTML=[...team].sort((a,b)=>(model.probs[b.name]||0)-(model.probs[a.name]||0)).map(p=>{let pm=scenarioMegaForPokemon(model,p.name,megaName),{pr,arr}=bestFor(p,pm),inCombo=arr.filter(x=>top.combo.includes(x.id)).sort((a,b)=>b.grade-a.grade),b=inCombo[0],safe=inCombo.filter(x=>x.grade>=4),prob=Math.round((model.probs[p.name]||0)*100),escape=safe.length?`${OWN[safe[0].id].name}으로 교체 가능`:`무상 교체 불가. ${inCombo.find(x=>x.grade>=2)?OWN[inCombo.find(x=>x.grade>=2).id].name+'을 안전 투입 후 처리':'현재 포켓몬으로 피해를 남기고 희생 교환'}`;if(b.grade>=4&&(model.probs[p.name]||0)>=.3)preserve.push(`${OWN[b.id].name}: ${p.name} 처리 전 체력·도구 보존`);if(b.grade<4&&(model.probs[p.name]||0)>=.3)avoid.push(`${p.name}: 강한 후출 답이 없다. 선대면 체크와 복수 처리 카드 두 장을 함께 남길 것`);return `<tr><td><b>${p.name}</b><br><small>선출 예상도 ${prob}점 · ${pr.precision}</small><br><small>${abilitySummary(p,pm)}</small></td><td>${defenseAxisText(p,pm)}</td><td><b>${OWN[b.id].name}</b></td><td>${gradeBadge(b.grade)}</td><td>${b.move}</td><td>${escape}</td><td>${b.note}</td></tr>`}).join('');
 if(team.some(p=>p.name==='망나뇽')){preserve.unshift('망나뇽: 초나열매 누리레느를 보존하고, 스텔스록·암석봉인·볼트체인지·탈 중 하나로 멀티스케일을 먼저 해제한다. 해제 후 안전 맞대면이면 누리레느가 조건부 강한 체크가 된다.');avoid.unshift('망나뇽: 10만볼트에 누리레느를 직접 교체하지 않는다. 먼저 멀티스케일을 깨거나 안전 투입 경로를 만든다.')}
 if(team.some(p=>p.name==='찌리배리')){
   const bellHard=top.combo.includes('venusaur')||top.combo.includes('garchomp');
   if(!bellHard)avoid.unshift('찌리배리: 추천 선출에 메가이상해꽃·한카리아스가 모두 없다. 트릭만으로 담당하지 말고 선출 자체를 재검토한다.');
   else preserve.unshift(`찌리배리: ${top.combo.includes('venusaur')?'메가이상해꽃':'한카리아스'}을 확인 전까지 보존한다.`);
   if(top.combo.includes('rotomh'))avoid.unshift('찌리배리에게 블라인드 트릭 금지: 게으름피우기·맹독·물붓기를 확인했을 때만 트릭. 볼트체인지에 묶이면 스카프 고속 피벗을 만들어준다.');
 }
 for(const p of team){let pm=scenarioMegaForPokemon(model,p.name,megaName),gap=axisGapForCombo(top.combo,p,pm),prob=model.probs[p.name]||0;if(gap&&prob>=.28&&!gap.hasWanted)avoid.unshift(`${p.name}: ${gap.d.label}. 추천 ${AXIS_LABEL[gap.wanted]}축 실질 타점이 부족하다. 타입상 유리해 보여도 장기전 돌파를 보장하지 않는다.`);else if(gap&&prob>=.28&&gap.hasWanted)preserve.push(`${p.name}: ${gap.d.label}이므로 ${OWN[gap.best.id].name}의 ${AXIS_LABEL[gap.best.cat]} ${gap.best.move} 돌파축을 보존한다.`)}
 if(!preserve.length)preserve.push('최유력 시나리오의 유일한 등급 4~5 담당을 상대가 확인되기 전에 소모하지 않습니다.');if(!avoid.length)avoid.push('등급 3 이하는 선대면 체크이므로 공격을 맞으며 교체하는 카운터로 취급하지 않습니다.');
 $('preserve').innerHTML=[...new Set(preserve)].map(x=>`<li>${x}</li>`).join('');$('avoid').innerHTML=[...new Set(avoid)].map(x=>`<li>${x}</li>`).join('');$('resultPanel').scrollIntoView({behavior:'smooth'});
}

export function form(){team=getTeam();if(!team)return;$('formPanel').classList.remove('hidden');$('preview').innerHTML=team.map(p=>`<span class="epill">${p.name}</span>`).join('');let mh=inferMega(team,''),opts=[`<option value="">자동 추정: ${mh.name||'불명'} (${mh.confidence})</option>`];for(const p of team)for(const x of (DATA.megaOptions[p.name]||[]))opts.push(`<option>${x}</option>`);$('megaSelect').innerHTML=opts.join('');let prev=$('manualLeadSelect').value;$('manualLeadSelect').innerHTML='<option value="">자동 예측에 맡기기</option>'+team.map(p=>`<option value="${p.name}">${p.name} 선봉으로 예상</option>`).join('');if(team.some(p=>p.name===prev))$('manualLeadSelect').value=prev;$('formPanel').scrollIntoView({behavior:'smooth'})}

export function fillLiveBase(){let opts=DATA.roster.map(p=>`<option value="${p.name}">#${p.rank} ${p.name}</option>`).join('');$('liveEnemy').innerHTML=opts;$('liveOwn').innerHTML=IDS.map(id=>`<option value="${id}">${OWN[id].name}</option>`).join('')}

export function renderManual(){let q=norm($('manualSearch').value),filter=$('gradeFilter').value,rows=[];for(const p of DATA.roster){if(q&&!norm(p.name).includes(q)&&!cho(p.name).startsWith(cho($('manualSearch').value)))continue;let autoMega=(DATA.megaOptions[p.name]||[]).length===1?(DATA.megaOptions[p.name][0]):'',{pr,arr,best}=bestFor(p,autoMega),second=arr[1],def=defenseProfile(p,autoMega),bm=bestAbilityMove(p,best.id,autoMega);if(filter==='noCounter'&&best.grade>=4)continue;if(filter==='precise'&&pr.precision!=='최신 검증')continue;rows.push(`<tr><td>${p.rank}</td><td><b>${p.name}</b><br><small>${battleTypes(p,autoMega).join('·')}${autoMega?' ('+autoMega+')':''}</small></td><td>${pr.precision}</td><td><small>${abilitySummary(p,autoMega)}</small><br><small><b>적용:</b> ${abilityImpact(p,autoMega)}</small></td><td>${defenseAxisText(p,autoMega)}</td><td><b>${OWN[best.id].name}</b><br><small>2차 ${OWN[second.id].name}</small><br><small>${bm.axisNote||'타입·특성 우선'}</small></td><td>${gradeBadge(best.grade)}</td><td><b>${best.move}</b><br>${pr.winPlan}</td><td>${best.note}</td></tr>`)}$('manualBody').innerHTML=rows.join('')}

export function modalRender(){let q=$('modalSearch').value,items=search(q,[],235);$('rosterGrid').innerHTML=items.map(p=>`<button class="ritem" data-n="${p.name}"><b>${p.name}</b><small>#${p.rank} · ${p.types.join('/')}</small></button>`).join('');$('rosterGrid').querySelectorAll('[data-n]').forEach(x=>x.onclick=()=>{choose(states[modalSlot],DATA.roster.find(p=>p.name===x.dataset.n),true);$('modal').classList.add('hidden')})}

// === v4.3 행동순서·동적 타입 감사 엔진 ===

export function fillLiveMovesV42(){let p=DATA.roster.find(x=>x.name===$('liveEnemy').value);if(!p)return;let old=$('revealedMove').value,moves=enemyMoveScenariosV42(p,'','');$('revealedMove').innerHTML='<option value="">자동: 가장 위험한 표준기</option>'+moves.map(m=>`<option value="${m.name}">${m.name}${m.usage?' · '+m.usage+'%':''}</option>`).join('');if(moves.some(m=>m.name===old))$('revealedMove').value=old}

export function fillLiveFormsV42(){let p=DATA.roster.find(x=>x.name===$('liveEnemy').value);if(!p)return;let forms=DATA.megaOptions[p.name]||[],old=$('liveMega').value;$('liveMega').innerHTML='<option value="">자동·기본/메가 범위</option><option value="base">기본 폼 확정</option>'+forms.map(x=>`<option value="${x}">${x} 확정</option>`).join('');if([...forms,'base',''].includes(old))$('liveMega').value=old;fillLiveMovesV42()}

export function resolveLiveMegaV42(p){let v=$('liveMega').value;return v==='base'?'':v}


export function fillLive(){ fillLiveBase(); fillLiveFormsV42(); $('liveEnemy').onchange=fillLiveFormsV42; }
export function live(){
  let p=DATA.roster.find(x=>x.name===$('liveEnemy').value),id=$('liveOwn').value,megaName=resolveLiveMegaV42(p),boost=+$('boost').value,hp=+$('hp').value,enemyState=$('enemyState').value,itemState=$('itemState').value,speedState=$('speedState').value,proteanState=$('proteanState').value,revealedMove=$('revealedMove').value,fieldState=$('fieldState').value,{pr,arr}=bestFor(p,megaName),cur=arr.find(x=>x.id===id),audit=exchangeAudit(p,id,megaName,{recommendedMove:cur.move,speedState,proteanState,revealedMove,itemState,fieldState});
  let adjust=Math.min(cur.grade,audit.gradeCap)-(boost>=2?2:boost===1?1:0)-(hp<=40?1:0),conditional='';
  if(p.name==='망나뇽'&&id==='prim'){if(enemyState==='chipped'&&boost===0&&itemState==='ready'&&hp===100){adjust=Math.max(adjust,4);conditional='초나열매 보존＋거의 풀피＋멀티스케일 해제 상태의 안전 맞대면. 문포스를 바로 누르고 날개쉬기는 앙코르.'}else if(enemyState==='full'&&boost===0&&itemState==='ready'&&hp===100){adjust=Math.max(adjust,3);conditional='깨끗한 선대면은 가능하지만 10만볼트를 맞으며 들어가는 후출 카운터는 아니다.'}}
  let safe=arr.filter(x=>x.id!==id&&x.grade>=4+(boost>=1?1:0)),checks=arr.filter(x=>x.id!==id&&x.grade===3),rev=arr.filter(x=>x.id!==id&&x.grade===2),action='';
  if(adjust>=3)action=`<b>유지 가능:</b> ${cur.move}. ${conditional||cur.note}`;else if(safe.length)action=`<b>즉시 교체:</b> ${safe.map(x=>OWN[x.id].name).join(', ')}. 현재 대면은 선공권·타입 변화까지 포함하면 유지 불가.`;else action=`<b>무상 교체 불가:</b> 피해·스피드 제어를 남기거나 희생 후 ${rev.length?rev.map(x=>OWN[x.id].name).join(', '):checks.length?checks.map(x=>OWN[x.id].name).join(', '):'가장 빠른 후속 카드'} 투입.`;
  let moveLine=audit.enemyMove?`${audit.enemyMove.name} · ${audit.enemyMove.cat==='physical'?'물리':'특수'} · 우리에게 ${audit.enemyMove.mult}배`:'표준 공격기 불명',typeLine=audit.typeShift?`${audit.enemyMove.name} 사용 직전/동시에 ${audit.afterTypes.join('/')} 타입으로 변화 → ${audit.ownMove} ${audit.responseMult}배`:'이번 계산에서 선행 타입 변화 없음';
  $('liveResult').innerHTML=`<h3>${OWN[id].name} vs ${megaName||p.name}: ${gradeBadge(Math.max(0,adjust))}</h3><p>${action}</p><div class="tree-row ${adjust<=1?'danger':adjust>=3?'safe':''}"><b>행동순서 판정</b><p><b>${audit.relation.label}</b> · 상대 속도 ${Math.round(audit.relation.enemy.min)}${audit.relation.enemy.min===audit.relation.enemy.max?'':'~'+Math.round(audit.relation.enemy.max)} / 우리 ${audit.relation.own}<br><b>상대 예상 첫 타:</b> ${moveLine}<br><b>특성 후 타입:</b> ${typeLine}<br><b>등급 제한 근거:</b> ${audit.reasons.join(' / ')||'추가 제한 없음'}</p></div><p><b>안전 후출:</b> ${safe.length?safe.map(x=>OWN[x.id].name).join(', '):'없음'}<br><b>선대면 체크:</b> ${checks.length?checks.map(x=>OWN[x.id].name).join(', '):'없음'}<br><b>복수 처리:</b> ${rev.length?rev.map(x=>OWN[x.id].name).join(', '):'없음'}</p><p><b>상대 특성:</b> ${abilitySummary(p,megaName)}<br><b>내구 투자:</b> ${defenseProfile(p,megaName).label}<br><b>상대 패턴:</b> ${pr.pattern}<br><b>승리 플랜:</b> ${pr.winPlan}</p>`;$('liveResult').classList.remove('hidden');
}

export class SimulatorApp {
  bootstrap(){
    renderTeam();slots();fillLive();renderManual();
    $('sampleBtn').onclick=()=>{['마스카나','파라블레이즈','갸라도스','하마돈','찌리배리','마폭시'].forEach((n,i)=>choose(states[i],DATA.roster.find(p=>p.name===n),false));form()};
    $('resetBtn').onclick=()=>{slots();['formPanel','resultPanel','matchPanel','planPanel'].forEach(x=>$(x).classList.add('hidden'))};
    $('analyzeBtn').onclick=analyze;$('allBtn').onclick=()=>{$('modal').classList.remove('hidden');modalSlot=states.findIndex(x=>!x.selected);if(modalSlot<0)modalSlot=0;modalRender()};
    $('closeModal').onclick=()=>$('modal').classList.add('hidden');$('modalSearch').oninput=modalRender;$('liveBtn').onclick=live;$('manualSearch').oninput=renderManual;$('gradeFilter').onchange=renderManual;
    document.addEventListener('click',e=>{if(e.target.id==='modal')$('modal').classList.add('hidden');if(e.target.id==='formPanel')return});
    document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');['select','live','manual','audit'].forEach(x=>$('tab-'+x).classList.toggle('hidden',x!==b.dataset.tab));if(b.dataset.tab==='manual')renderManual()});
  }
}
